name: Ansible test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-playbook:
    name: Run playbook
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Update apt-get
        run: sudo apt-get update


      - name: Update apt-get
        run: sudo apt-get upgrade -y


      - name: Install Ansible
        run: sudo apt-get install -y ansible


      - name: Run Ansible Playbook
        run: ansible-playbook -K -i inventory bootstrap-all.yml
        env:
          ANSIBLE_BECOME_PASS: ${{ secrets.SUDO_PASSWORD }}
